### ISSUE TITLE
Improve snapshots.mitmproxy.org

### ISSUE THREAD

**Issue by mhils** [mitmproxy/release#3]
- Set up https://github.com/pypa/setuptools_scm for mitmproxy, netlib and pathod.
- Build a simple HTTPS Server (Flask or anything else will do) for snapshots.mitmproxy.org
  - Travis and AppVeyor will `POST` binary snapshots (plus version information)
  - Server puts binaries them in the right subdirectory, following the version schem we envison.
  - Server adds symlink for the latest release.

**Comment by dufferzafar** [comment]
@mhils I understand what the Flask server needs to do and all, but not how the setuptools_scm repo fits in the scene. Can you please shed some light on this?

**Comment by dufferzafar** [comment]
As far as I can understand, we'll use that to get package version numbers from git tag etc. Is that correct?

**Comment by mhils** [comment]
@dufferzafar: These two are somewhat related - currently, each snapshot overwrites the latest one if they share the same tag, which kind of sucks. Using setuptools_scm, we'd have consistent version tags to send to the server. 
Strictly speaking, you are right, these task can be separated.

**Comment by Kriechi** [comment]
closed by d3a9a6ba9520c5c80de3433697a8f5f30fa33c67
